/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quiz1;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class framequiz1 extends javax.swing.JFrame {
    String jenis_kopi="";
    int harga_kopi;
    int epesanan;
    int eharga;
    int ebayar;
    

    /**
     * Creates new form framequiz1
     */
    public framequiz1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pelanggan = new javax.swing.JLabel();
        kopi = new javax.swing.JLabel();
        pesanan = new javax.swing.JLabel();
        hitungpesanan = new javax.swing.JButton();
        harga = new javax.swing.JLabel();
        jumharga = new javax.swing.JLabel();
        hapus = new javax.swing.JButton();
        pesan = new javax.swing.JButton();
        ePelanggan = new javax.swing.JTextField();
        eHarga = new javax.swing.JTextField();
        ePesanan = new javax.swing.JTextField();
        eJumharga = new javax.swing.JTextField();
        eKopi = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Sigmar One", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("_WELCOME TO CAFENA_");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 350, 26));

        pelanggan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pelanggan.setForeground(new java.awt.Color(255, 255, 255));
        pelanggan.setText("NAMA PELANGGAN");
        jPanel1.add(pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 74, -1, -1));

        kopi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        kopi.setForeground(new java.awt.Color(255, 255, 255));
        kopi.setText("JENIS KOPI");
        jPanel1.add(kopi, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 109, -1, -1));

        pesanan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pesanan.setForeground(new java.awt.Color(255, 255, 255));
        pesanan.setText("JUMLAH PESANAN");
        jPanel1.add(pesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 179, -1, -1));

        hitungpesanan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        hitungpesanan.setText("HITUNG PESANAN");
        hitungpesanan.setBorder(null);
        hitungpesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungpesananActionPerformed(evt);
            }
        });
        jPanel1.add(hitungpesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 205, 128, 23));

        harga.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        harga.setForeground(new java.awt.Color(255, 255, 255));
        harga.setText("HARGA KOPI");
        jPanel1.add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 144, -1, -1));

        jumharga.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jumharga.setForeground(new java.awt.Color(255, 255, 255));
        jumharga.setText("JUMLAH HARGA");
        jPanel1.add(jumharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 246, -1, -1));

        hapus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        hapus.setText("HAPUS");
        hapus.setBorder(null);
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel1.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 275, 72, 20));

        pesan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pesan.setText("PESAN");
        pesan.setBorder(null);
        pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesanActionPerformed(evt);
            }
        });
        jPanel1.add(pesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 275, 69, 23));

        ePelanggan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(ePelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 71, 195, -1));

        eHarga.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(eHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 141, 195, -1));

        ePesanan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(ePesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 176, 195, -1));

        eJumharga.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(eJumharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 240, 195, -1));

        eKopi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        eKopi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH JENIS KOPI", "KOPI ARABICA", "KOPI ROBUSTA", "KOPI LIBERIKA", "KOPI LUWAK", "KOPI TUBRUK", "KOPI LATTE", "KOPI AMERICANO" }));
        eKopi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eKopiActionPerformed(evt);
            }
        });
        jPanel1.add(eKopi, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 106, 195, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz1/gambarrr1.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 400, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eKopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eKopiActionPerformed
        String jenis_kopi = (String)eKopi.getSelectedItem();
        if (jenis_kopi=="PILIH JENIS KOPI"){
        }else if(jenis_kopi=="KOPI ARABICA"){
            harga_kopi=15000;
        }else if(jenis_kopi=="KOPI ROBUSTA"){
            harga_kopi=20000;
        }else if(jenis_kopi=="KOPI LIBERIKA"){
            harga_kopi=35000;
        }else if(jenis_kopi=="KOPI LUWAK"){
            harga_kopi=30000;
        }else if(jenis_kopi=="KOPI TUBRUK"){
            harga_kopi=25000;
        }else if(jenis_kopi=="KOPI LATTE"){
            harga_kopi=40000;
        }else if(jenis_kopi=="KOPI AMERICANO"){
            harga_kopi=45000;
        }
        
        eHarga.setText(""+ harga_kopi);
    }//GEN-LAST:event_eKopiActionPerformed

    private void hitungpesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungpesananActionPerformed
        eharga = Integer.parseInt(eHarga.getText());
        epesanan = Integer.parseInt(ePesanan.getText());
        
        ebayar = eharga*epesanan;
        eJumharga.setText(""+ebayar);
    }//GEN-LAST:event_hitungpesananActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        ePelanggan.setText(""); 
        eKopi.setSelectedIndex(0);
        eHarga.setText("");
        ePesanan.setText("");
        eJumharga.setText("");
    }//GEN-LAST:event_hapusActionPerformed

    private void pesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanActionPerformed
        String nama,jeniskopi;
        int hargakopi,pesanan,jumlahharga;
        nama = ePelanggan.getText();
        jeniskopi = (String) eKopi.getSelectedItem();
        hargakopi = Integer.parseInt(eHarga.getText());
        pesanan = Integer.parseInt(ePesanan.getText());
        jumlahharga = Integer.parseInt(eJumharga.getText());
   
        JOptionPane.showMessageDialog(this, "NAMA PELANGGAN: " + nama 
            + "\nJENIS KOPI: " + jeniskopi  
            + "\nHARGA KOPI: " + hargakopi 
            + "\nJUMLAH PESANAN: " + pesanan  
            + "\nJUMLAH HARGA: " + jumlahharga 
        );
    }//GEN-LAST:event_pesanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framequiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framequiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framequiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framequiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framequiz1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eHarga;
    private javax.swing.JTextField eJumharga;
    private javax.swing.JComboBox<String> eKopi;
    private javax.swing.JTextField ePelanggan;
    private javax.swing.JTextField ePesanan;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel harga;
    private javax.swing.JButton hitungpesanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jumharga;
    private javax.swing.JLabel kopi;
    private javax.swing.JLabel pelanggan;
    private javax.swing.JButton pesan;
    private javax.swing.JLabel pesanan;
    // End of variables declaration//GEN-END:variables
}
